// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwjfimrqpomeqlsrquej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3amZpbXJxcG9tZXFsc3JxdWVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3NTYxMDUsImV4cCI6MjA3NzMzMjEwNX0.aSeibreuGq97MM-5ZU9uQ5Qb0muyBaBTuN8Zvz1_R8M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});